---
Name: silverstripe-taskforms
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Dev\TaskRunner:
    class: Hamaka\TaskForms\Controllers\GroupedTaskRunner
SilverStripe\Dev\DevelopmentAdmin:
  registered_controllers:
    tasks:
      controller: 'Hamaka\TaskForms\Controllers\GroupedTaskRunner'
      links:
        tasks: 'See a list of build tasks to run'
